### ISSUE TITLE
Cropping input from a USB cam

### ISSUE THREAD

**Issue by clementpouget** [SchwarzNeuroconLab/DeepLabStream#106]
Hi,
Thanks for the development of DLStream. I've been using it for a short while in my experiments, and so far had no problem with it. I'm trying to setup a new experiment in which it would be very practical for us to be able to crop the image before the analysis is done with DLStream (the experiment is an open field, and we often have arduinos, computers etc. showing in the full picture of the camera if we use the full 1920x1080 stream). Do you know of any simple way to do that ? I am not proficient with python but can understand it / modify a few things if needed.

Thanks for your help!
Clément Pouget

**Comment by clementpouget** [comment]
Quick update on the issue: I found the crop hidden in advanced_settings.ini . It seems that the crop works fine while using DLStream, but for now I am unable to open the corresponding saved .avi file. I am suspecting this is because of a bug with only native aspect ratios being able to encode into avi vids, because even without cropping if I stray away from 1080p, 720p etc. the .avi will not save.

I will try to work on this a little bit, and come back with my solution if I find one!

**Comment by clementpouget** [comment]
After reading through the code for a while, I managed to find the problem:

In deeplabstream.py, when creating the video file to save:
(lines 298-304)

>     def create_videofiles(self):
>         """
>         Create video files dictionary by cameras names
>         """
>         self._video_files = create_video_files(
>             OUT_DIR, self.enabled_cameras, RESOLUTION, FRAMERATE, self._video_codec
>         )

The resolution of the .avi is set to the resolution set in the settings.ini, not the corrected cropped resolution, hence the inability to read the file afterwards.

I fixed it by adding @ line 302:

>         if CROP:
>             SAVE_RESOLUTION = (CROP_X[1]-CROP_X[0],CROP_Y[1]-CROP_Y[0])
>         else:
>             SAVE_RESOLUTION = RESOLUTION
> 

this is probably somewhat barbaric, but the fix works for me.

I hope this can be useful, might be worth adding to the main files :)

**Comment by JensBlack** [comment]
Thank you for using DLStream and great catch! I'll take a look at the issue and get back to you. Thanks also for suggesting a solution.

**Comment by JensBlack** [comment]
I added and pushed your suggested solution. I think it is a good simple solution. Thank you for bringing it to my attention.
