### ISSUE TITLE
Add setup.py and upload to PyPI

### ISSUE THREAD

**Issue by eggplants** [SchwarzNeuroconLab/DeepLabStream#43]
**Describe the solution you'd like**
To make installation easier, please add setup.py and upload to PyPI.

**Comment by JensBlack** [comment]
Thank you for your request, eggplants.

The current version of DLStream includes some changes in the base code (namely experiments.py), so burying DLStream deep in any environment structure is inconvenient for now. However, we are already thinking about how to optimize this. I've included your suggestion on our roadmap :)
